# Form implementation generated from reading ui file 'correos_electronicos.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Correos(object):
    def setupUi(self, Dialog_Correos):
        Dialog_Correos.setObjectName("Dialog_Correos")
        Dialog_Correos.resize(400, 360)
        self.pushButton_aceptar = QtWidgets.QPushButton(parent=Dialog_Correos)
        self.pushButton_aceptar.setGeometry(QtCore.QRect(130, 320, 75, 24))
        self.pushButton_aceptar.setObjectName("pushButton_aceptar")
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=Dialog_Correos)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(210, 320, 75, 24))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.pushButton_borrar = QtWidgets.QPushButton(parent=Dialog_Correos)
        self.pushButton_borrar.setGeometry(QtCore.QRect(310, 320, 75, 24))
        self.pushButton_borrar.setObjectName("pushButton_borrar")
        self.label = QtWidgets.QLabel(parent=Dialog_Correos)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_correo = QtWidgets.QLineEdit(parent=Dialog_Correos)
        self.lineEdit_correo.setGeometry(QtCore.QRect(20, 40, 361, 22))
        self.lineEdit_correo.setClearButtonEnabled(True)
        self.lineEdit_correo.setObjectName("lineEdit_correo")
        self.label_2 = QtWidgets.QLabel(parent=Dialog_Correos)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_preferencia = QtWidgets.QComboBox(parent=Dialog_Correos)
        self.comboBox_preferencia.setGeometry(QtCore.QRect(140, 80, 51, 22))
        self.comboBox_preferencia.setObjectName("comboBox_preferencia")
        self.comboBox_preferencia.addItem("")
        self.comboBox_preferencia.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_Correos)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 361, 191))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_observ = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.textEdit_observ.setGeometry(QtCore.QRect(10, 30, 341, 151))
        font = QtGui.QFont()
        font.setBold(False)
        self.textEdit_observ.setFont(font)
        self.textEdit_observ.setObjectName("textEdit_observ")

        self.retranslateUi(Dialog_Correos)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Correos)

    def retranslateUi(self, Dialog_Correos):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Correos.setWindowTitle(_translate("Dialog_Correos", "Correos electrónicos"))
        self.pushButton_aceptar.setText(_translate("Dialog_Correos", "Aceptar"))
        self.pushButton_cancelar.setText(_translate("Dialog_Correos", "Cancelar"))
        self.pushButton_borrar.setText(_translate("Dialog_Correos", "Borrar"))
        self.label.setText(_translate("Dialog_Correos", "Correo electrónico"))
        self.lineEdit_correo.setPlaceholderText(_translate("Dialog_Correos", "Correo electrónico"))
        self.label_2.setText(_translate("Dialog_Correos", "Mail preferido"))
        self.comboBox_preferencia.setItemText(0, _translate("Dialog_Correos", "Si"))
        self.comboBox_preferencia.setItemText(1, _translate("Dialog_Correos", "No"))
        self.groupBox_2.setTitle(_translate("Dialog_Correos", "Observaciones"))
        self.textEdit_observ.setHtml(_translate("Dialog_Correos", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_observ.setPlaceholderText(_translate("Dialog_Correos", "Observaciones sobre el correo electrónico"))
