# Form implementation generated from reading ui file 'telefonos.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Telefonos(object):
    def setupUi(self, Dialog_Telefonos):
        Dialog_Telefonos.setObjectName("Dialog_Telefonos")
        Dialog_Telefonos.resize(400, 360)
        self.pushButton_aceptar = QtWidgets.QPushButton(parent=Dialog_Telefonos)
        self.pushButton_aceptar.setGeometry(QtCore.QRect(130, 320, 75, 24))
        self.pushButton_aceptar.setObjectName("pushButton_aceptar")
        self.pushButton_cancelar = QtWidgets.QPushButton(parent=Dialog_Telefonos)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(210, 320, 75, 24))
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.pushButton_borrar = QtWidgets.QPushButton(parent=Dialog_Telefonos)
        self.pushButton_borrar.setGeometry(QtCore.QRect(310, 320, 75, 24))
        self.pushButton_borrar.setObjectName("pushButton_borrar")
        self.label = QtWidgets.QLabel(parent=Dialog_Telefonos)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_tlfno = QtWidgets.QLineEdit(parent=Dialog_Telefonos)
        self.lineEdit_tlfno.setGeometry(QtCore.QRect(20, 40, 361, 22))
        self.lineEdit_tlfno.setClearButtonEnabled(True)
        self.lineEdit_tlfno.setObjectName("lineEdit_tlfno")
        self.label_2 = QtWidgets.QLabel(parent=Dialog_Telefonos)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_preferencia = QtWidgets.QComboBox(parent=Dialog_Telefonos)
        self.comboBox_preferencia.setGeometry(QtCore.QRect(140, 80, 51, 22))
        self.comboBox_preferencia.setObjectName("comboBox_preferencia")
        self.comboBox_preferencia.addItem("")
        self.comboBox_preferencia.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog_Telefonos)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 120, 361, 191))
        font = QtGui.QFont()
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_observ = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.textEdit_observ.setGeometry(QtCore.QRect(10, 30, 341, 151))
        font = QtGui.QFont()
        font.setBold(False)
        self.textEdit_observ.setFont(font)
        self.textEdit_observ.setObjectName("textEdit_observ")

        self.retranslateUi(Dialog_Telefonos)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Telefonos)

    def retranslateUi(self, Dialog_Telefonos):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Telefonos.setWindowTitle(_translate("Dialog_Telefonos", "Teléfonos"))
        self.pushButton_aceptar.setText(_translate("Dialog_Telefonos", "Aceptar"))
        self.pushButton_cancelar.setText(_translate("Dialog_Telefonos", "Cancelar"))
        self.pushButton_borrar.setText(_translate("Dialog_Telefonos", "Borrar"))
        self.label.setText(_translate("Dialog_Telefonos", "Teléfono"))
        self.lineEdit_tlfno.setPlaceholderText(_translate("Dialog_Telefonos", "Teléfono"))
        self.label_2.setText(_translate("Dialog_Telefonos", "Teléfono preferido"))
        self.comboBox_preferencia.setItemText(0, _translate("Dialog_Telefonos", "Si"))
        self.comboBox_preferencia.setItemText(1, _translate("Dialog_Telefonos", "No"))
        self.groupBox_2.setTitle(_translate("Dialog_Telefonos", "Observaciones"))
        self.textEdit_observ.setPlaceholderText(_translate("Dialog_Telefonos", "Observaciones sobre el teléfono"))
